<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
	
	<ItemGroup>
		<PackageReference Include="Amazon.Lambda.Core" Version="3.1.1" />
		<PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" Version="3.0.0" />
		<PackageReference Include="Amazon.Lambda.SQSEvents" Version="3.0.0" />
		<PackageReference Include="AWSSDK.SimpleNotificationService" Version="4.0.100.3" />
		<PackageReference Include="AWSSDK.SQS" Version="4.0.0.6" />
		<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.10" />
		<PackageReference Include="Polly" Version="8.6.6" />
	</ItemGroup>
	
	<ItemGroup>
		<ProjectReference Include="..\TradingApp.Business\TradingApp.Business.csproj" />
		<ProjectReference Include="..\TradingApp.Domain\TradingApp.Domain.csproj" />
		<ProjectReference Include="..\TradingApp.Events\TradingApp.Events.csproj" />
	</ItemGroup>
	
</Project>
